project_id = "culsencadxqxfphownik"

[functions.iol-auth]
verify_jwt = false

[functions.iol-panel]
verify_jwt = false

[functions.yfinance-info]
verify_jwt = false

[functions.macro-ar]
verify_jwt = false

[functions.yf-history]
verify_jwt = false

[functions.yf-earnings]
verify_jwt = false

[functions.auto-portfolio]
verify_jwt = false
